# Generated by Django 4.1 on 2023-02-13 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_certificate_cert_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 0, 37, 37, 934949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 0, 37, 37, 934949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 0, 37, 37, 934949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 0, 37, 37, 934949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 0, 37, 37, 934949, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 0, 37, 37, 934949, tzinfo=datetime.timezone.utc)),
        ),
    ]
