# Generated by Django 4.1.1 on 2023-02-13 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_certificate_cert_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Link'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_price',
            field=models.CharField(max_length=200, null=True, verbose_name='Event Price'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 34, 7, 516889, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 34, 7, 516889, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 34, 7, 516889, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 34, 7, 516889, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 34, 7, 516889, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 13, 7, 34, 7, 516889, tzinfo=datetime.timezone.utc)),
        ),
    ]
