# Generated by Django 4.1.1 on 2023-02-17 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_certificate_cert_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_price',
        ),
        migrations.AddField(
            model_name='event',
            name='event_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='user_approver',
            field=models.CharField(max_length=50, null=True, verbose_name='Approver Name'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 18, 15, 59, 844741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 18, 15, 59, 844741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 18, 15, 59, 844741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 18, 15, 59, 844741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_link',
            field=models.CharField(max_length=200, null=True, verbose_name='Zoom link'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 18, 15, 59, 844741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 17, 18, 15, 59, 844741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='register_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_payment_amount', models.IntegerField(default=0, null=True)),
                ('reg_proof_payment', models.FileField(null=True, upload_to=users.models.event_image_path)),
                ('reg_pmode', models.CharField(max_length=16, null=True, verbose_name='Event Payment')),
                ('reg_payment_status', models.CharField(default='PENDING', max_length=16)),
                ('reg_payment_date', models.DateTimeField(default=datetime.datetime(2023, 2, 17, 18, 15, 59, 844741, tzinfo=datetime.timezone.utc))),
                ('reg_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.event')),
                ('reg_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.membership')),
            ],
        ),
    ]
